name: Deploy SvelteKit SSR (build in CI)

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Build (CI)
        run: npm run build

      # Upload repo + build to server (excludes node_modules/.env)
      - name: Upload to server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='.env'"
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: '/var/www/bobthered.com/app'

      # Install ONLY runtime deps on server, then restart service
      - name: Install runtime & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd /var/www/bobthered.com/app
            npm ci --omit=dev
            sudo -n /usr/bin/systemctl restart sveltekit-bobthered
