name: Deploy SvelteKit SSR (adapter-node)

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Upload the repo to the server (skip git/.github/node_modules/.env)
      - name: Upload repo via rsync
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='.env'"
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: '/var/www/bobthered.com/app'

      # Install deps, build (npm/yarn/pnpm supported), then restart service
      - name: Build & restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd /var/www/bobthered.com/app

            # Ensure we don't accidentally skip devDependencies during build
            export NODE_ENV=
            export NPM_CONFIG_PRODUCTION=

            # Use the right package manager automatically
            if [ -f pnpm-lock.yaml ]; then
              corepack enable
              pnpm install --frozen-lockfile
              pnpm build
            elif [ -f yarn.lock ]; then
              corepack enable
              yarn install --frozen-lockfile
              yarn build
            elif [ -f package-lock.json ]; then
              npm ci
              npm run build
            else
              npm install
              npm run build
            fi

            # Restart the SSR service (passwordless via sudoers)
            sudo -n /usr/bin/systemctl restart sveltekit-bobthered
