name: Deploy (smoke test)

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run a remote command on the server (no sudo)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            mkdir -p /var/www/bobthered.com
            echo "Deployed from GitHub on $(date -u)" > /var/www/bobthered.com/DEPLOYED.txt
